###
# Mozilla Firefox Security Technical Implementation Guide :: Version 6, Release: 5 Benchmark Date: 26 Jul 2023
###
- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto
# Create distribution folder in Firefox Install directory
- name: Create distribution folder
  ansible.builtin.file:
    path: "{{ firefox_install_directory }}/distribution"
    mode: '0755'
    owner: root
    group: root
    state: directory
# Create Blank STIG Policy dictionary
- name: Create blank Policy
  ansible.builtin.set_fact:
    config:
      policies:

# Copy basic config files
# - name: Copy autoconfig.js file to host
#   ansible.builtin.copy:
#     src: autoconfig.js
#     dest: /usr/lib64/firefox/defaults/pref/autoconfig.js
#     mode: '0644'
#     owner: root
#     group: root
#     state: present
# - name: Determine if mozilla.cfg exists
#   ansible.builtin.stat:
#     path: /usr/lib64/firefox/mozilla.cfg
#   register: conf_file
# - name: Copy blank mozilla.cfg to host
#   ansible.builtin.copy:
#     src: mozilla.cfg
#     dest: /usr/lib64/firefox/mozilla.cfg
#     mode: '0644'
#     owner: root
#     group: root
#     state: present
#   when: conf_file.stat.exists is not defined  # File not present
# V-251545 - FFOX-00-000001 - The installed version of Firefox must be supported.

# V-251546 - FFOX-00-000002 - Firefox must be configured to allow only TLS 1.2 or above.
- name: FFOX-00-000002
  ansible.builtin.set_fact:
    config: "{{ config | ansible.builtin.combine(newelement, recursive=true) }}"
  vars:
    newelement:
      policies:
        SSLVersionMin: '{{ tls_min_version }}'
  with_dict: "{{ config }}"
  when:
    - DISA_STIG_FFOX_00_000002
# V-251547 - FFOX-00-000003 - Firefox must be configured to ask which certificate to present to a website when a certificate is required.
- name: FFOX-00-000003
  ansible.builtin.set_fact:
    config: "{{ config | ansible.builtin.combine(newelement, recursive=true) }}"
  vars:
    newelement:
      policies:
        Preferences:
          security.default_personal_cert:
            Value: "Ask Every Time"
            Status: "locked"
  with_dict: "{{ config }}"
  when:
    - DISA_STIG_FFOX_00_000003
# V-251548 - FFOX-00-000004 - Firefox must be configured to not automatically check for updated versions of installed search plugins.
# V-251549 - FFOX-00-000005 - Firefox must be configured to not automatically update installed add-ons and plugins.
# V-251550 - FFOX-00-000006 - Firefox must be configured to not automatically execute or download MIME types that are not authorized for auto-download.
# V-251551 - FFOX-00-000007 - Firefox must be configured to disable form fill assistance.
# V-251552 - FFOX-00-000008 - Firefox must be configured to not use a password store with or without a master password.
# V-251553 - FFOX-00-000009 - Firefox must be configured to block pop-up windows.
# V-251554 - FFOX-00-000010 - Firefox must be configured to prevent JavaScript from moving or resizing windows.
# V-251555 - FFOX-00-000011 - Firefox must be configured to prevent JavaScript from raising or lowering windows.
# V-251557 - FFOX-00-000013 - Firefox must be configured to disable the installation of extensions.
# V-251558 - FFOX-00-000014 - Background submission of information to Mozilla must be disabled.
# V-251559 - FFOX-00-000015 - Firefox development tools must be disabled.
# V-251560 - FFOX-00-000016 - Firefox must have the DoD root certificates installed.
# V-251562 - FFOX-00-000018 - Firefox must prevent the user from quickly deleting data.
# V-251563 - FFOX-00-000019 - Firefox private browsing must be disabled.
# V-251564 - FFOX-00-000020 - Firefox search suggestions must be disabled.
# V-251565 - FFOX-00-000021 - Firefox autoplay must be disabled.
# V-251566 - FFOX-00-000022 - Firefox network prediction must be disabled.
# V-251567 - FFOX-00-000023 - Firefox fingerprinting protection must be enabled.
# V-251568 - FFOX-00-000024 - Firefox cryptomining protection must be enabled.
# V-251569 - FFOX-00-000025 - Firefox Enhanced Tracking Protection must be enabled.
# V-251570 - FFOX-00-000026 - Firefox extension recommendations must be disabled.
# V-251571 - FFOX-00-000027 - Firefox deprecated ciphers must be disabled.
# V-251572 - FFOX-00-000028 - Firefox must not recommend extensions as the user is using the browser.
# V-251573 - FFOX-00-000029 - The Firefox New Tab page must not show Top Sites, Sponsored Top Sites, Pocket Recommendations, Sponsored Pocket Stories, Searches, Highlights, or Snippets.
# V-251577 - FFOX-00-000033 - Firefox must be configured so that DNS over HTTPS is disabled.
# V-251578 - FFOX-00-000034 - Firefox accounts must be disabled.
# V-251580 - FFOX-00-000036 - Firefox feedback reporting must be disabled.
# V-251581 - FFOX-00-000037 - Firefox encrypted media extensions must be disabled.
# V-252881 - FFOX-00-000017 - Firefox must be configured to not delete data upon shutdown.
# V-252908 - FFOX-00-000038 - Pocket must be disabled.
# V-252909 - FFOX-00-000039 - Firefox Studies must be disabled.
